In [1]:
import pandas as pd
pd.__version__

'3.0.3'

In [4]:
df=pd.DataFrame({
    "Name":["Ram","Hari"],
    "Age":[12,13,]
});

In [5]:
df

   Name  Age
0   Ram   12
1  Hari   13

In [6]:
df.head(1)

  Name  Age
0  Ram   12

In [11]:
df["Name"].head()

0     Ram
1    Hari
Name: Name, dtype: str

In [16]:
df.to_csv("Student.csv",index=False)

In [14]:
df=pd.read_csv("Student.csv")
df

   Name  Age
0   Ram   12
1  Hari   13

In [17]:
df["Dept"]=["IT","Management"]

In [18]:
df

   Name  Age        Dept
0   Ram   12          IT
1  Hari   13  Management

In [22]:
sorted_array=df.sort_values("Name",ascending=True);
sorted_array

   Name  Age        Dept
1  Hari   13  Management
0   Ram   12          IT

In [23]:
df.loc[df.Name=="Hari","Name"]="Ronish"

In [25]:
df.loc[len(df)]=["Dipesh",19,"MBA"]
df

     Name  Age        Dept
0     Ram   12          IT
1  Ronish   13  Management
2  Dipesh   19         MBA

In [34]:
df.drop(df.loc[df.Name=="Dipesh"].index,inplace=True)
df

     Name  Age        Dept
0     Ram   12          IT
1  Ronish   13  Management

##Kendal Notation

A: Arrival process
S=Service time distribution
m=Number of services
B=Number of buffers{system capacity}
K=Population size
S(E)=Service Notation